version: 2.1
orb:
    ko: kieran-osgood/update-git-tags-orb@dev:alpha
jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - ko/main
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - ko/run